hhvm:
    image: diegomarangoni/hhvm:fastcgi
    container_name: hhvm
    working_dir: /data
    env_file: .env
    volumes:
        - ./public_html/:/data
    links:
        - mysql
nginx:
    image: nginx
    container_name: saro-sms-dashboard-nginx
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/sites/:/etc/nginx/sites-available:ro
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
        - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
        - ./nginx/start.sh:/etc/nginx/start.sh
        - ./nginx/logs/:/logs
        - ./public_html/:/data
    links:
        - hhvm
    command: /etc/nginx/start.sh

mysql:
    image: mariadb:10.1
    container_name: saro-sms-dashboard-mysql
    env_file: .env
    environment:
        # Fix https://goo.gl/fUTycl
        MYSQL_HOST:
    ports:
        - "3311:3306"
    volumes:
        - ./db_dump/:/docker-entrypoint-initdb.d